CREATE TABLE books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  description TEXT,
  age_range VARCHAR(10) NOT NULL,
  purpose ENUM('learning', 'entertainment') NOT NULL,
  genre VARCHAR(100),
  price DECIMAL(6,2) NOT NULL,
  tags TEXT,
  rating DECIMAL(2,1) DEFAULT 0.0
);

-- Real book data for the database
INSERT INTO books (title, author, description, age_range, purpose, genre, price, tags)
VALUES
('Where the Wild Things Are', 'Maurice Sendak', 'The story of Max, who dresses in his wolf costume and sails to where the wild things are.', '4-8', 'entertainment', 'fantasy', 17.99, 'classic,imagination,adventure'),
('Charlotte''s Web', 'E.B. White', 'The story of a pig named Wilbur and his friendship with a barn spider named Charlotte.', '8-12', 'entertainment', 'fiction', 14.99, 'friendship,animals,classic'),
('The Very Hungry Caterpillar', 'Eric Carle', 'Follows the progress of a hungry caterpillar as he eats his way through a varied and large quantity of food before pupating and emerging as a butterfly.', '2-5', 'learning', 'picture book', 12.99, 'nature,counting,transformation'),
('Goodnight Moon', 'Margaret Wise Brown', 'In a great green room, a young rabbit says goodnight to all the familiar things in the room.', '1-4', 'entertainment', 'bedtime story', 9.99, 'bedtime,classic,calming'),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'The first novel in the Harry Potter series that follows a young wizard''s journey at Hogwarts School of Witchcraft and Wizardry.', '9-12', 'entertainment', 'fantasy', 24.99, 'magic,wizards,adventure'),
('The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 'Four siblings travel through a wardrobe to the magical land of Narnia and help a lion defeat a witch.', '8-12', 'entertainment', 'fantasy', 18.99, 'magic,adventure,classic'),
('A Wrinkle in Time', 'Madeleine L''Engle', 'Meg Murry and her friends become involved with unearthly strangers in a search for her father, who disappeared while engaged in secret work for the government.', '10-14', 'entertainment', 'science fiction', 12.99, 'space,time travel,coming-of-age'),
('Matilda', 'Roald Dahl', 'The story of a gifted young girl with psychokinetic powers who triumphs over her unkind parents and the terrifying school headmistress.', '8-12', 'entertainment', 'fiction', 15.99, 'humor,school,powers'),
('The Giving Tree', 'Shel Silverstein', 'A moving parable about the gift of giving and the capacity to love.', '4-8', 'learning', 'picture book', 16.99, 'kindness,generosity,nature'),
('Oh, The Places You''ll Go!', 'Dr. Seuss', 'The journey of life and its challenges in Dr. Seuss''s signature style.', '5-9', 'learning', 'picture book', 18.99, 'inspiration,life lessons,rhyming'),
('The Cat in the Hat', 'Dr. Seuss', 'A mischievous cat in a tall striped hat arrives at a home to entertain two bored children on a rainy day.', '3-7', 'entertainment', 'picture book', 14.99, 'rhyming,imagination,humor'),
('Bridge to Terabithia', 'Katherine Paterson', 'The story of a young boy who creates a secret kingdom in the woods with his best friend.', '9-12', 'entertainment', 'fiction', 13.99, 'friendship,imagination,loss'),
('The Hobbit', 'J.R.R. Tolkien', 'Follows the quest of Bilbo Baggins to win a share of the treasure guarded by Smaug the dragon.', '10-14', 'entertainment', 'fantasy', 22.99, 'adventure,dragons,quest'),
('Diary of a Wimpy Kid', 'Jeff Kinney', 'The adventures of Greg Heffley, a middle-school student navigating the challenges of adolescence.', '8-12', 'entertainment', 'humor', 13.99, 'school,humor,illustrated'),
('Wonder', 'R.J. Palacio', 'The story of Auggie Pullman, a boy with facial differences who enters fifth grade at a mainstream school for the first time.', '9-12', 'learning', 'realistic fiction', 16.99, 'empathy,inclusion,school'),
('Percy Jackson and the Lightning Thief', 'Rick Riordan', 'The story of a young boy who discovers he is a demigod and must prevent a war between the gods.', '10-14', 'entertainment', 'fantasy', 17.99, 'mythology,adventure,powers'),
('Brown Bear, Brown Bear, What Do You See?', 'Bill Martin Jr.', 'A story about different colored animals and what they see.', '2-5', 'learning', 'picture book', 9.99, 'colors,animals,rhyming'),
('Holes', 'Louis Sachar', 'A boy is sent to a detention center and must dig holes every day, but discovers more than dirt.', '10-14', 'entertainment', 'adventure', 14.99, 'friendship,justice,mystery'),
('The Giver', 'Lois Lowry', 'In a seemingly perfect society, a boy is chosen to be the receiver of memories of the time before emotion was eliminated.', '12-14', 'entertainment', 'dystopian', 15.99, 'society,memory,choices'),
('Charlie and the Chocolate Factory', 'Roald Dahl', 'The adventures of young Charlie Bucket inside the chocolate factory of eccentric chocolatier Willy Wonka.', '8-12', 'entertainment', 'fantasy', 14.99, 'candy,adventure,humor'),
('The Lorax', 'Dr. Seuss', 'The Lorax speaks for the trees against the greedy Once-ler who is destroying the environment.', '5-9', 'learning', 'picture book', 16.99, 'environment,conservation,rhyming'),
('Curious George', 'H.A. Rey', 'The adventures of a curious monkey named George and the Man with the Yellow Hat.', '3-7', 'entertainment', 'picture book', 12.99, 'animals,curiosity,adventure'),
('The Tale of Peter Rabbit', 'Beatrix Potter', 'The mischievous Peter Rabbit disobeys his mother and ventures into Mr. McGregor''s garden.', '3-7', 'entertainment', 'picture book', 11.99, 'animals,classic,adventure'),
('James and the Giant Peach', 'Roald Dahl', 'An orphan boy enters a gigantic, magical peach and has adventures with six garden insects.', '8-12', 'entertainment', 'fantasy', 13.99, 'magic,adventure,friendship'),
('The Secret Garden', 'Frances Hodgson Burnett', 'A young orphaned girl discovers a magical garden hidden in her uncle''s house.', '9-12', 'entertainment', 'classic', 14.99, 'nature,friendship,growth'),
('If You Give a Mouse a Cookie', 'Laura Numeroff', 'A circular tale describing the chaos that ensues when a little boy gives a cookie to a mouse.', '3-7', 'entertainment', 'picture book', 10.99, 'humor,animals,cause-effect'),
('Anne of Green Gables', 'L.M. Montgomery', 'The story of an orphan girl who brings joy and love to the lives of an elderly brother and sister.', '9-12', 'entertainment', 'classic', 15.99, 'coming-of-age,friendship,imagination'),
('The Wonderful Wizard of Oz', 'L. Frank Baum', 'Dorothy is swept away from her Kansas farm to the magical Land of Oz and embarks on a quest to meet a wizard.', '8-12', 'entertainment', 'fantasy', 14.99, 'adventure,magic,friendship'),
('Chicka Chicka Boom Boom', 'Bill Martin Jr.', 'The letters of the alphabet race each other up a coconut tree.', '2-5', 'learning', 'picture book', 11.99, 'alphabet,rhyming,counting'),
('The BFG', 'Roald Dahl', 'A young orphan girl befriends a benevolent giant who takes her to Giant Country.', '8-12', 'entertainment', 'fantasy', 15.99, 'friendship,giants,dreams'),
('Green Eggs and Ham', 'Dr. Seuss', 'A character called "Sam-I-am" pesters an unnamed character to try green eggs and ham.', '3-7', 'entertainment', 'picture book', 12.99, 'rhyming,humor,food'),
('Ramona Quimby, Age 8', 'Beverly Cleary', 'The adventures of spirited Ramona Quimby as she navigates third grade.', '7-10', 'entertainment', 'realistic fiction', 13.99, 'school,family,humor'),
('Corduroy', 'Don Freeman', 'A teddy bear in a department store searches for his missing button so he can find a home.', '2-5', 'entertainment', 'picture book', 10.99, 'friendship,adventure,toys'),
('The Lightning Thief', 'Rick Riordan', 'Percy Jackson discovers he is a demigod and must find Zeus''s master lightning bolt to prevent a war between the gods.', '10-14', 'entertainment', 'fantasy', 17.99, 'mythology,adventure,friendship'),
('Stellaluna', 'Janell Cannon', 'A young bat is separated from her mother and raised by a family of birds.', '4-8', 'learning', 'picture book', 13.99, 'animals,differences,acceptance'),
('Frog and Toad Are Friends', 'Arnold Lobel', 'A series of five short stories about the friendship between Frog and Toad.', '4-8', 'entertainment', 'early reader', 12.99, 'friendship,animals,humor'),
('Guess How Much I Love You', 'Sam McBratney', 'Little Nutbrown Hare tries to express his love for Big Nutbrown Hare.', '3-7', 'entertainment', 'picture book', 11.99, 'love,family,bedtime'),
('Number the Stars', 'Lois Lowry', 'During the Nazi occupation of Denmark, a 10-year-old girl helps her Jewish friend escape to Sweden.', '10-14', 'learning', 'historical fiction', 15.99, 'friendship,courage,history'),
('Make Way for Ducklings', 'Robert McCloskey', 'A pair of mallards look for the perfect spot to raise their young in Boston.', '3-7', 'entertainment', 'picture book', 14.99, 'animals,family,city'),
('Sarah, Plain and Tall', 'Patricia MacLachlan', 'A prairie family searches for a new mother and wife through a newspaper ad.', '8-12', 'entertainment', 'historical fiction', 13.99, 'family,pioneer,love'),
('Amelia Bedelia', 'Peggy Parish', 'A literal-minded housekeeper causes chaos when she follows her employer''s instructions too exactly.', '5-8', 'entertainment', 'humor', 11.99, 'wordplay,humor,misunderstandings'),
('The Magic School Bus series', 'Joanna Cole', 'Ms. Frizzle and her class take magical field trips to learn about science and nature.', '7-10', 'learning', 'science', 15.99, 'education,adventure,science'),
('Pippi Longstocking', 'Astrid Lindgren', 'The adventures of a young girl with superhuman strength and independent spirit.', '7-10', 'entertainment', 'adventure', 14.99, 'humor,independence,strength'),
('The Wind in the Willows', 'Kenneth Grahame', 'The adventures of anthropomorphic animals: Mole, Rat, Toad, and Badger.', '8-12', 'entertainment', 'classic', 16.99, 'animals,friendship,adventure'),
('Harold and the Purple Crayon', 'Crockett Johnson', 'A boy creates a world of his own with a purple crayon.', '3-6', 'entertainment', 'picture book', 10.99, 'imagination,creativity,adventure'),
('Madeline', 'Ludwig Bemelmans', 'The adventures of a young girl in a boarding school in Paris.', '3-7', 'entertainment', 'picture book', 13.99, 'Paris,school,adventure'),
('Island of the Blue Dolphins', 'Scott O''Dell', 'A young girl survives by herself on an island off the California coast.', '9-12', 'entertainment', 'adventure', 15.99, 'survival,courage,nature'),
('The Little Prince', 'Antoine de Saint-Exupéry', 'A pilot stranded in the desert meets a young prince who has fallen to Earth from a tiny asteroid.', '10-14', 'learning', 'fantasy', 17.99, 'philosophy,friendship,imagination'),
('The Phantom Tollbooth', 'Norton Juster', 'A bored young boy drives through a magical tollbooth to a land where he must rescue princesses Rhyme and Reason.', '9-12', 'entertainment', 'fantasy', 16.99, 'wordplay,adventure,imagination');
