CREATE TABLE IF NOT EXISTS books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  description TEXT,
  from_age INT,
  to_age INT,
  purpose VARCHAR(100) NOT NULL,
  genre VARCHAR(100),
  price DECIMAL(6,2) NOT NULL,
  tags TEXT,
  quantity INT NOT NULL DEFAULT 0
);

-- Real book data for the database (100+ diverse, real records, sorted by title)
INSERT INTO books (title, author, description, from_age, to_age, purpose, genre, price, tags, quantity)
VALUES
('A Brief History of Time', 'Stephen Hawking', 'A landmark volume in science writing by one of the great minds of our time.', 16, 99, 'learning', 'science', 14.99, 'cosmology,physics,science', 9),
('A Thousand Splendid Suns', 'Khaled Hosseini', 'The story of two women in Afghanistan and their struggle for survival.', 16, 99, 'learning', 'historical fiction', 13.99, 'afghanistan,women,survival', 8),
('A Wrinkle in Time', 'Madeleine L''Engle', 'Meg Murry and her friends become involved with unearthly strangers in a search for her father, who disappeared while engaged in secret work for the government.', 10, 14, 'entertainment', 'science fiction', 12.99, 'space,time travel,coming-of-age', 19),
('Alexander Hamilton', 'Ron Chernow', 'A biography of the American founding father.', 16, 99, 'learning', 'biography', 16.99, 'history,politics,biography', 8),
('Anne of Green Gables', 'L.M. Montgomery', 'An imaginative orphan girl finds a home with two elderly siblings on Prince Edward Island.', 9, 99, 'entertainment', 'classic', 12.99, 'imagination,orphan,classic', 8),
('Atomic Habits', 'James Clear', 'An easy and proven way to build good habits and break bad ones.', 18, 99, 'learning', 'self-help', 15.99, 'habits,productivity,psychology', 9),
('Becoming', 'Michelle Obama', 'The memoir of the former First Lady of the United States.', 18, 99, 'inspiration', 'memoir', 16.99, 'memoir,women,leadership', 10),
('Bird by Bird', 'Anne Lamott', 'Some instructions on writing and life.', 16, 99, 'learning', 'reference', 11.99, 'writing,life,reference', 7),
('Born a Crime', 'Trevor Noah', 'Stories from a South African childhood under apartheid.', 16, 99, 'learning', 'memoir', 14.99, 'apartheid,humor,history', 8),
('Bridge to Terabithia', 'Katherine Paterson', 'The story of a young boy who creates a secret kingdom in the woods with his best friend.', 9, 12, 'entertainment', 'fiction', 13.99, 'friendship,imagination,loss', 10),
('Brown Bear, Brown Bear, What Do You See?', 'Bill Martin Jr.', 'A story about different colored animals and what they see.', 2, 5, 'learning', 'picture book', 9.99, 'colors,animals,rhyming', 7),
('Charlie and the Chocolate Factory', 'Roald Dahl', 'The adventures of young Charlie Bucket inside the chocolate factory of eccentric chocolatier Willy Wonka.', 8, 12, 'entertainment', 'fantasy', 14.99, 'candy,adventure,humor', 20),
('Cosmos', 'Carl Sagan', 'A personal voyage through the universe.', 15, 99, 'learning', 'science', 15.99, 'astronomy,universe,science', 8),
('Diary of a Wimpy Kid', 'Jeff Kinney', 'The adventures of Greg Heffley, a middle-school student navigating the challenges of adolescence.', 8, 12, 'entertainment', 'humor', 13.99, 'school,humor,illustrated', 4),
('Divergent', 'Veronica Roth', 'In a dystopian future, society is divided into five factions.', 14, 99, 'entertainment', 'dystopian', 13.99, 'factions,identity,adventure', 10),
('Dracula', 'Bram Stoker', 'The classic vampire tale of Count Dracula''s attempt to move from Transylvania to England.', 15, 99, 'entertainment', 'horror', 13.99, 'vampires,horror,classic', 7),
('Drawing on the Right Side of the Brain', 'Betty Edwards', 'A course in enhancing creativity and artistic confidence.', 14, 99, 'learning', 'reference', 13.99, 'art,creativity,reference', 7),
('Educated', 'Tara Westover', 'A memoir about a woman who grows up in a strict and abusive household in rural Idaho but eventually escapes to learn about the wider world through education.', 18, 99, 'learning', 'memoir', 14.99, 'education,memoir,overcoming', 7),
('Fahrenheit 451', 'Ray Bradbury', 'A dystopian future where books are outlawed and burned.', 15, 99, 'learning', 'dystopian', 13.99, 'books,censorship,classic', 8),
('Frankenstein', 'Mary Shelley', 'A scientist creates a sentient creature in a scientific experiment gone wrong.', 15, 99, 'learning', 'horror', 12.99, 'science,creation,classic', 9),
('Grit', 'Angela Duckworth', 'The power of passion and perseverance.', 18, 99, 'inspiration', 'self-help', 13.99, 'perseverance,success,psychology', 7),
('Goodnight Moon', 'Margaret Wise Brown', 'A young rabbit says goodnight to all the familiar things in the room.', 1, 4, 'entertainment', 'bedtime story', 8.99, 'bedtime,classic,calming', 9),
('Hatchet', 'Gary Paulsen', 'A boy survives a plane crash and must fend for himself in the Canadian wilderness.', 10, 14, 'learning', 'adventure', 11.99, 'survival,wilderness,coming-of-age', 8),
('Heidi', 'Johanna Spyri', 'A young girl is sent to live with her grandfather in the Swiss Alps.', 7, 99, 'entertainment', 'classic', 9.99, 'alps,grandparent,classic', 7),
('Holes', 'Louis Sachar', 'A boy is sent to a detention center and must dig holes every day, but discovers more than dirt.', 10, 14, 'entertainment', 'adventure', 14.99, 'friendship,justice,mystery', 3),
('I Know Why the Caged Bird Sings', 'Maya Angelou', 'The first of Angelou''s autobiographies, describing her childhood and adolescence.', 15, 99, 'learning', 'memoir', 13.99, 'memoir,race,coming-of-age', 9),
('Into the Wild', 'Jon Krakauer', 'The story of Chris McCandless, who ventured into the Alaskan wilderness.', 17, 99, 'learning', 'adventure', 12.99, 'wilderness,adventure,biography', 6),
('Jane Eyre', 'Charlotte Brontë', 'An orphaned girl becomes a governess and falls in love with her employer.', 15, 99, 'entertainment', 'romance', 13.99, 'love,independence,classic', 11),
('Life of Pi', 'Yann Martel', 'A boy survives a shipwreck and shares a lifeboat with a Bengal tiger.', 14, 99, 'learning', 'adventure', 13.99, 'survival,faith,animals', 9),
('Little Women', 'Louisa May Alcott', 'The lives of the four March sisters during the American Civil War.', 12, 99, 'learning', 'classic', 13.99, 'family,growth,classic', 14),
('Long Walk to Freedom', 'Nelson Mandela', 'The autobiography of the first black president of South Africa.', 18, 99, 'inspiration', 'memoir', 15.99, 'autobiography,freedom,history', 7),
('Man''s Search for Meaning', 'Viktor E. Frankl', 'A Holocaust survivor''s lessons for spiritual survival.', 18, 99, 'inspiration', 'memoir', 13.99, 'holocaust,meaning,psychology', 8),
('Mastering the Art of French Cooking', 'Julia Child', 'A classic guide to French cuisine.', 16, 99, 'learning', 'reference', 16.99, 'cooking,french,reference', 8),
('Matilda', 'Roald Dahl', 'The story of a gifted young girl with psychokinetic powers who triumphs over her unkind parents and the terrifying school headmistress.', 8, 12, 'entertainment', 'fiction', 15.99, 'humor,school,powers', 11),
('Meditations', 'Marcus Aurelius', 'A series of personal writings by the Roman Emperor.', 18, 99, 'inspiration', 'philosophy', 13.99, 'stoicism,philosophy,classic', 7),
('Moby-Dick', 'Herman Melville', 'Captain Ahab''s obsessive quest to kill the white whale.', 16, 99, 'learning', 'adventure', 15.99, 'whale,obsession,classic', 8),
('Night', 'Elie Wiesel', 'A memoir about surviving the Holocaust.', 15, 99, 'learning', 'memoir', 12.99, 'holocaust,memoir,history', 8),
('Oh, The Places You''ll Go!', 'Dr. Seuss', 'The journey of life and its challenges in Dr. Seuss''s signature style.', 5, 9, 'learning', 'picture book', 18.99, 'inspiration,life lessons,rhyming', 14),
('On Writing: A Memoir of the Craft', 'Stephen King', 'Part memoir, part master class by one of the bestselling authors of all time.', 16, 99, 'learning', 'memoir', 12.99, 'writing,memoir,craft', 8),
('Percy Jackson and the Lightning Thief', 'Rick Riordan', 'The story of a young boy who discovers he is a demigod and must prevent a war between the gods.', 10, 14, 'entertainment', 'fantasy', 17.99, 'mythology,adventure,powers', 19),
('Pride and Prejudice', 'Jane Austen', 'A romantic novel about manners, upbringing, morality, and marriage in early 19th-century England.', 14, 99, 'entertainment', 'romance', 13.99, 'romance,society,classic', 11),
('Quiet: The Power of Introverts in a World That Can''t Stop Talking', 'Susan Cain', 'A book that champions the introvert''s cause.', 18, 99, 'learning', 'nonfiction', 13.99, 'introverts,psychology,society', 6),
('Salt, Fat, Acid, Heat', 'Samin Nosrat', 'Mastering the elements of good cooking.', 16, 99, 'learning', 'reference', 14.99, 'cooking,science,reference', 6),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'A narrative of humanity''s creation and evolution.', 18, 99, 'learning', 'nonfiction', 17.99, 'history,science,humanity', 9),
('Slaughterhouse-Five', 'Kurt Vonnegut', 'Billy Pilgrim becomes unstuck in time after surviving the bombing of Dresden in WWII.', 17, 99, 'learning', 'science fiction', 14.99, 'war,time travel,classic', 6),
('Steve Jobs', 'Walter Isaacson', 'The biography of Apple co-founder Steve Jobs.', 16, 99, 'learning', 'biography', 15.99, 'technology,innovation,biography', 9),
('The 7 Habits of Highly Effective People', 'Stephen R. Covey', 'A guide to personal and professional effectiveness.', 18, 99, 'learning', 'self-help', 16.99, 'habits,leadership,success', 10),
('The Adventures of Huckleberry Finn', 'Mark Twain', 'Huck Finn and Jim, a runaway slave, travel down the Mississippi River.', 12, 99, 'learning', 'classic', 11.99, 'adventure,freedom,classic', 9),
('The Adventures of Tom Sawyer', 'Mark Twain', 'A young boy grows up along the Mississippi River.', 9, 99, 'entertainment', 'classic', 10.99, 'adventure,childhood,classic', 12),
('The Alchemist', 'Paulo Coelho', 'A shepherd boy travels from Spain to Egypt in search of treasure and discovers his personal legend.', 15, 99, 'inspiration', 'adventure', 14.99, 'philosophy,adventure,dreams', 13),
('The Art of War', 'Sun Tzu', 'An ancient Chinese military treatise dating from the Late Spring and Autumn Period.', 16, 99, 'learning', 'philosophy', 12.99, 'strategy,war,philosophy', 9),
('The Art Spirit', 'Robert Henri', 'A classic work on the nature of art.', 16, 99, 'inspiration', 'reference', 12.99, 'art,creativity,classic', 5),
('The Book Thief', 'Markus Zusak', 'A young girl living in Nazi Germany finds solace by stealing books and sharing them with others.', 13, 99, 'learning', 'historical fiction', 16.99, 'wwii,books,courage', 6),
('The Call of the Wild', 'Jack London', 'A dog named Buck is stolen from his home and sold into the brutal life of an Alaskan sled dog.', 12, 99, 'learning', 'adventure', 13.99, 'dogs,alaska,survival', 9),
('The Cat in the Hat', 'Dr. Seuss', 'A mischievous cat in a tall striped hat arrives at a home to entertain two bored children on a rainy day.', 3, 7, 'entertainment', 'picture book', 14.99, 'rhyming,imagination,humor', 10),
('The Catcher in the Rye', 'J.D. Salinger', 'Holden Caulfield recounts days in New York after being expelled from prep school.', 15, 99, 'entertainment', 'classic', 14.99, 'adolescence,identity,classic', 7),
('The Color Purple', 'Alice Walker', 'A story of African American women in early 20th-century rural Georgia.', 16, 99, 'learning', 'historical fiction', 14.99, 'race,women,classic', 7),
('The Curious Incident of the Dog in the Night-Time', 'Mark Haddon', 'A boy with autism investigates the death of a neighbor''s dog.', 13, 99, 'learning', 'mystery', 12.99, 'autism,mystery,coming-of-age', 7),
('The Da Vinci Code', 'Dan Brown', 'A symbologist and a cryptologist uncover a religious mystery.', 17, 99, 'entertainment', 'thriller', 14.99, 'mystery,religion,thriller', 10),
('The Diary of a Young Girl', 'Anne Frank', 'The wartime diary of Anne Frank, a Jewish girl in hiding.', 12, 99, 'learning', 'memoir', 11.99, 'holocaust,diary,history', 10),
('The Double Helix', 'James D. Watson', 'The discovery of the structure of DNA.', 16, 99, 'learning', 'biography', 13.99, 'science,dna,history', 8),
('The Elements of Style', 'William Strunk Jr. and E.B. White', 'A guide to writing well.', 14, 99, 'learning', 'reference', 9.99, 'writing,style,reference', 10),
('The Emperor of All Maladies', 'Siddhartha Mukherjee', 'A biography of cancer.', 18, 99, 'learning', 'nonfiction', 15.99, 'cancer,medicine,history', 7),
('The Fault in Our Stars', 'John Green', 'Two teenagers with cancer fall in love after meeting at a support group.', 14, 99, 'inspiration', 'young adult', 12.99, 'romance,illness,young adult', 9),
('The Fannie Farmer Cookbook', 'Fannie Merritt Farmer', 'A classic American cookbook.', 14, 99, 'learning', 'reference', 13.99, 'cooking,recipes,reference', 5),
('The Giver', 'Lois Lowry', 'In a seemingly perfect society, a boy is chosen to be the receiver of memories of the time before emotion was eliminated.', 12, 14, 'entertainment', 'dystopian', 15.99, 'society,memory,choices', 2),
('The Giving Tree', 'Shel Silverstein', 'A moving parable about the gift of giving and the capacity to love.', 4, 8, 'learning', 'picture book', 16.99, 'kindness,generosity,nature', 5),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A journalist and a hacker investigate a decades-old disappearance.', 18, 99, 'entertainment', 'mystery', 15.99, 'mystery,crime,thriller', 8),
('The Grapes of Wrath', 'John Steinbeck', 'A family migrates from Oklahoma to California during the Great Depression.', 16, 99, 'learning', 'historical fiction', 15.99, 'migration,poverty,classic', 7),
('The Handmaid''s Tale', 'Margaret Atwood', 'A dystopian future where women are forced into reproductive servitude.', 17, 99, 'learning', 'dystopian', 14.99, 'dystopia,women,oppression', 8),
('The Help', 'Kathryn Stockett', 'A young white woman and two black maids in 1960s Mississippi form an unlikely friendship.', 16, 99, 'learning', 'historical fiction', 12.99, 'race,friendship,1960s', 7),
('The Hobbit', 'J.R.R. Tolkien', 'Bilbo Baggins embarks on a quest to win a share of treasure guarded by a dragon.', 10, 99, 'entertainment', 'fantasy', 19.99, 'adventure,dragons,quest,classic', 15),
('The Hunger Games', 'Suzanne Collins', 'A girl volunteers to take her sister''s place in a televised fight to the death.', 13, 99, 'entertainment', 'dystopian', 14.99, 'survival,rebellion,adventure', 15),
('The Iliad', 'Homer', 'The story of the Trojan War and the Greek siege of Troy.', 15, 99, 'learning', 'epic', 16.99, 'war,greek,classic', 9),
('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 'The story of the woman whose cancer cells were harvested without her knowledge.', 16, 99, 'learning', 'biography', 13.99, 'science,ethics,history', 8),
('The Joy of Cooking', 'Irma S. Rombauer', 'A classic cookbook for home cooks.', 14, 99, 'learning', 'reference', 15.99, 'cooking,recipes,reference', 10),
('The Jungle Book', 'Rudyard Kipling', 'The adventures of Mowgli, a boy raised by wolves in the Indian jungle.', 7, 99, 'entertainment', 'adventure', 11.99, 'animals,jungle,classic', 8),
('The Kite Runner', 'Khaled Hosseini', 'A story of friendship and redemption set in Afghanistan.', 16, 99, 'learning', 'historical fiction', 13.99, 'afghanistan,redemption,friendship', 9),
('The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 'Four siblings travel through a wardrobe to the magical land of Narnia and help a lion defeat a witch.', 8, 12, 'entertainment', 'fantasy', 18.99, 'magic,adventure,classic', 6),
('The Little Prince', 'Antoine de Saint-Exupéry', 'A young prince explores the universe, learning about love, loss, and human nature.', 8, 99, 'inspiration', 'fantasy', 12.99, 'philosophy,adventure,classic', 13),
('The Man Who Knew Infinity', 'Robert Kanigel', 'The biography of mathematician Srinivasa Ramanujan.', 16, 99, 'learning', 'biography', 12.99, 'mathematics,india,biography', 7),
('The Maze Runner', 'James Dashner', 'A boy wakes up in a mysterious maze with no memory of how he got there.', 13, 99, 'entertainment', 'science fiction', 12.99, 'maze,survival,adventure', 11),
('The Odyssey', 'Homer', 'The epic journey of Odysseus as he returns home from the Trojan War.', 15, 99, 'learning', 'epic', 16.99, 'adventure,journey,classic', 10),
('The Old Man and the Sea', 'Ernest Hemingway', 'An aging fisherman struggles with a giant marlin far out in the Gulf Stream.', 14, 99, 'inspiration', 'classic', 12.99, 'fishing,struggle,classic', 10),
('The Origin of Species', 'Charles Darwin', 'The foundation of evolutionary biology.', 16, 99, 'learning', 'science', 14.99, 'evolution,biology,classic', 6),
('The Outsiders', 'S.E. Hinton', 'A coming-of-age novel about rival teenage gangs in Oklahoma.', 13, 99, 'learning', 'young adult', 10.99, 'gangs,identity,classic', 7),
('The Picture of Dorian Gray', 'Oscar Wilde', 'A man remains young while his portrait ages and records his sins.', 16, 99, 'entertainment', 'classic', 13.99, 'vanity,morality,classic', 6),
('The Power of Habit', 'Charles Duhigg', 'An exploration of the science behind habit creation and reformation.', 18, 99, 'learning', 'nonfiction', 14.99, 'habits,psychology,science', 7),
('The Prince', 'Niccolò Machiavelli', 'A 16th-century political treatise.', 18, 99, 'learning', 'philosophy', 12.99, 'politics,philosophy,classic', 6),
('The Republic', 'Plato', 'A Socratic dialogue concerning justice and the order and character of the just city-state and the just man.', 18, 99, 'learning', 'philosophy', 14.99, 'justice,philosophy,classic', 8),
('The Road', 'Cormac McCarthy', 'A father and son journey through a post-apocalyptic America.', 17, 99, 'learning', 'dystopian', 15.99, 'survival,apocalypse,family', 5),
('The Road to Character', 'David Brooks', 'An exploration of the deeper values that should inform our lives.', 18, 99, 'inspiration', 'nonfiction', 15.99, 'character,values,philosophy', 6),
('The Secret Garden', 'Frances Hodgson Burnett', 'A lonely girl discovers a hidden, neglected garden and brings it back to life.', 8, 99, 'inspiration', 'classic', 11.99, 'nature,growth,friendship', 6),
('The Secret Life of Bees', 'Sue Monk Kidd', 'A young girl escapes her troubled life and finds solace in a South Carolina town.', 14, 99, 'inspiration', 'historical fiction', 13.99, 'bees,healing,coming-of-age', 8),
('The Selfish Gene', 'Richard Dawkins', 'A gene-centered view of evolution.', 16, 99, 'learning', 'science', 13.99, 'evolution,biology,science', 7),
('The Silver Spoon', 'The Silver Spoon Kitchen', 'The bible of authentic Italian home cooking.', 14, 99, 'learning', 'reference', 15.99, 'cooking,italian,reference', 7),
('The Soul of a New Machine', 'Tracy Kidder', 'A behind-the-scenes look at the development of a new computer in the 1980s.', 18, 99, 'learning', 'nonfiction', 13.99, 'technology,computers,history', 6),
('The Story of Art', 'E.H. Gombrich', 'A comprehensive introduction to art history.', 15, 99, 'learning', 'reference', 14.99, 'art,history,reference', 8),
('The Structure of Scientific Revolutions', 'Thomas S. Kuhn', 'A landmark in intellectual history.', 18, 99, 'learning', 'science', 13.99, 'science,philosophy,history', 5),
('The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'A counterintuitive approach to living a good life.', 18, 99, 'inspiration', 'self-help', 14.99, 'self-help,philosophy,life', 8),
('The Swiss Family Robinson', 'Johann David Wyss', 'A family is shipwrecked on a deserted island and must learn to survive.', 8, 99, 'learning', 'adventure', 10.99, 'survival,island,family', 10),
('The Tale of Peter Rabbit', 'Beatrix Potter', 'Peter Rabbit disobeys his mother and sneaks into Mr. McGregor''s garden.', 3, 7, 'entertainment', 'children''s', 8.99, 'animals,garden,classic', 11),
('The Very Hungry Caterpillar', 'Eric Carle', 'Follows the progress of a hungry caterpillar as he eats his way through a varied and large quantity of food before pupating and emerging as a butterfly.', 2, 5, 'learning', 'picture book', 12.99, 'nature,counting,transformation', 8),
('The Wind in the Willows', 'Kenneth Grahame', 'The adventures of Mole, Rat, Toad, and Badger along the riverbank.', 7, 99, 'entertainment', 'classic', 10.99, 'animals,friendship,adventure', 6),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'A groundbreaking tour of the mind and explanation of the two systems that drive the way we think.', 18, 99, 'learning', 'nonfiction', 15.99, 'psychology,decision-making,science', 8),
('To Kill a Mockingbird', 'Harper Lee', 'A novel about the serious issues of rape and racial inequality, seen through the eyes of young Scout Finch in the Deep South.', 13, 99, 'learning', 'classic', 18.99, 'justice,race,coming-of-age,classic', 12),
('Treasure Island', 'Robert Louis Stevenson', 'A boy embarks on a perilous journey to find buried treasure.', 10, 99, 'entertainment', 'adventure', 11.99, 'pirates,treasure,classic', 12),
('Ways of Seeing', 'John Berger', 'A look at how we view art.', 16, 99, 'learning', 'reference', 12.99, 'art,perception,reference', 6),
('Where the Wild Things Are', 'Maurice Sendak', 'The story of Max, who dresses in his wolf costume and sails to where the wild things are.', 4, 8, 'entertainment', 'fantasy', 17.99, 'classic,imagination,adventure', 12),
('Wild', 'Cheryl Strayed', 'A woman hikes the Pacific Crest Trail alone to recover from personal tragedy.', 18, 99, 'inspiration', 'memoir', 13.99, 'adventure,healing,memoir', 7),
('Wonder', 'R.J. Palacio', 'The story of Auggie Pullman, a boy with facial differences who enters fifth grade at a mainstream school for the first time.', 9, 12, 'learning', 'realistic fiction', 16.99, 'empathy,inclusion,school', 16),
('Wuthering Heights', 'Emily Brontë', 'A tale of passion and revenge on the Yorkshire moors.', 16, 99, 'entertainment', 'romance', 12.99, 'revenge,moors,classic', 8)
;
